const express = require('express');
const { Pool } = require('pg');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const path = require('path');
const multer = require('multer');
const fs = require('fs');
const crypto = require('crypto');
const os = require('os');
const { spawn, execFile } = require('child_process');
const { v2: cloudinary } = require('cloudinary');

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true
});

/* مسارات FFmpeg/FFprobe: من الحزم المرفقة إن وُجدت، وإلا من PATH النظام */
let FFMPEG = 'ffmpeg';
let FFPROBE = 'ffprobe';
try { FFMPEG = require('@ffmpeg-installer/ffmpeg').path; } catch {}
try { FFPROBE = require('@ffprobe-installer/ffprobe').path; } catch {}

/* حدود المعالجة (قابلة للتعديل من متغيرات البيئة) — الافتراضات متحفظة لتناسب Render Free */
const MAX_PROCESS_PIXELS = Number(process.env.MAX_PROCESS_PIXELS) || 2560 * 1440;
const MAX_PROCESS_SECONDS = Number(process.env.MAX_PROCESS_SECONDS) || 180;
const PROCESS_TIMEOUT_MS = Number(process.env.PROCESS_TIMEOUT_MS) || 8 * 60 * 1000;
const FFMPEG_THREADS = String(process.env.FFMPEG_THREADS || 1);
const FFMPEG_PRESET = process.env.FFMPEG_PRESET || 'veryfast';
const CLOUDINARY_MAX_BYTES = 95 * 1024 * 1024;

const SECRET =
  process.env.JWT_SECRET || crypto.randomBytes(32).toString('hex');

if (!process.env.JWT_SECRET) {
  console.warn(
    'تنبيه: JWT_SECRET غير مضبوط، سيتسجّل خروج الجميع عند كل إعادة تشغيل.'
  );
}

if (!process.env.DATABASE_URL) {
  console.error('خطأ: DATABASE_URL غير مضبوط.');
  process.exit(1);
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
});

fs.mkdirSync('uploads', { recursive: true });

async function initDB() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT UNIQUE NOT NULL,
      pass TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS videos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      file TEXT NOT NULL,
      caption TEXT,
      created BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())
    );

    CREATE TABLE IF NOT EXISTS likes (
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
      PRIMARY KEY (user_id, video_id)
    );

    CREATE TABLE IF NOT EXISTS comments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
      body TEXT NOT NULL,
      created BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())
    );

    CREATE TABLE IF NOT EXISTS follows (
      follower INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      followee INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      PRIMARY KEY (follower, followee)
    );
  `);

  /* ---- جديد: جدول القصص (آمن ولا يؤثر على الجداول الحالية) ---- */
  await pool.query(`
    CREATE TABLE IF NOT EXISTS stories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      file TEXT NOT NULL,
      type TEXT NOT NULL CHECK (type IN ('image', 'video')),
      public_id TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours')
    );

    CREATE INDEX IF NOT EXISTS stories_expires_idx ON stories (expires_at);
    CREATE INDEX IF NOT EXISTS stories_user_idx ON stories (user_id);
  `);

  /* ---- جديد: عمود اختياري لمعلومات الفيديو (الدقة/الفريمات) — لا يمس البيانات القديمة ---- */
  await pool.query(`ALTER TABLE videos ADD COLUMN IF NOT EXISTS meta JSONB;`);

  console.log('تم الاتصال بقاعدة بيانات Neon بنجاح.');
}
const app = express();

app.use(express.json());

app.use((req, res, next) => {
  try {
    const auth = (req.headers.authorization || '').replace('Bearer ', '');
    req.u = jwt.verify(auth, SECRET);
  } catch {
    req.u = null;
  }

  next();
});
const must = (req, res) =>
  req.u ||
  (res.status(401).json({ error: 'سجّل الدخول أولًا' }), null);

/* التخزين المؤقت على القرص (بدل الذاكرة) كي لا تمتلئ ذاكرة Render Free بملفات كبيرة */
const diskStore = multer.diskStorage({
  destination: os.tmpdir(),
  filename: (req, file, cb) => {
    const ext = path
      .extname(file.originalname || '')
      .replace(/[^.\w]/g, '')
      .slice(0, 8);
    cb(null, 'pulse-in-' + crypto.randomBytes(8).toString('hex') + ext);
  }
});

const rmFile = (p) => {
  if (p) fs.unlink(p, () => {});
};

const up = multer({
  storage: diskStore,
  limits: {
    fileSize: 100 * 1024 * 1024
  },
  fileFilter: (req, file, cb) => {
cb(null, file.mimetype.startsWith('video/'));  }
});

const storyUp = multer({
  storage: diskStore,
  limits: {
    fileSize: 100 * 1024 * 1024
  },
  fileFilter: (req, file, cb) => {
    cb(null, /^(image|video)\//.test(file.mimetype));
  }
});

const token = (u) =>
  jwt.sign(
    {
      id: u.id,
      name: u.name
    },
    SECRET,
    {
      expiresIn: '30d'
    }
  );

const cred = (b) =>
  /^[A-Za-z0-9_]{3,20}$/.test(b.name || '') &&
  (b.pass || '').length >= 6;


/* =========================
   Register
========================= */

app.post('/api/register', async (req, res) => {
  if (!cred(req.body)) {
    return res.status(400).json({
      error:
        'الاسم 3-20 حرفًا إنجليزيًا/أرقام/_ وكلمة المرور 6 على الأقل'
    });
  }

  try {
    const hashed = bcrypt.hashSync(req.body.pass, 10);

    const result = await pool.query(
      `
      INSERT INTO users(name, pass)
      VALUES($1, $2)
      RETURNING id, name
      `,
      [req.body.name, hashed]
    );

    const u = result.rows[0];

    res.json({
      token: token(u),
      name: u.name
    });
  } catch (err) {
    if (err.code === '23505') {
      return res.status(409).json({
        error: 'الاسم مستخدم'
      });
    }

    console.error(err);
    res.status(500).json({
      error: 'حدث خطأ في الخادم'
    });
  }
});


/* =========================
   Login
========================= */

app.post('/api/login', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT * FROM users WHERE name = $1',
      [req.body.name || '']
    );

    const u = result.rows[0];

    if (!u || !bcrypt.compareSync(req.body.pass || '', u.pass)) {
      return res.status(401).json({
        error: 'بيانات الدخول غير صحيحة'
      });
    }

    res.json({
      token: token(u),
      name: u.name
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'حدث خطأ في الخادم'
    });
  }
});


/* =========================
   Feed
========================= */

const SEL = `
  SELECT
    v.id,
    v.file,
    v.caption,
    v.meta,
    u.name,

    (SELECT COUNT(*)
     FROM likes
     WHERE video_id = v.id) AS likes,

    (SELECT COUNT(*)
     FROM comments
     WHERE video_id = v.id) AS comments,

    EXISTS(
      SELECT 1
      FROM likes
      WHERE video_id = v.id
      AND user_id = $1
    ) AS liked,

    EXISTS(
      SELECT 1
      FROM follows
      WHERE follower = $1
      AND followee = v.user_id
    ) AS following

  FROM videos v
  JOIN users u ON u.id = v.user_id
`;


app.get('/api/feed', async (req, res) => {
  try {
    const me = req.u ? req.u.id : 0;

    // تبويب «تتابع»: فيديوهات الأشخاص الذين يتابعهم المستخدم فقط
    const followingOnly = req.query.tab === 'following';

    if (followingOnly && !must(req, res)) return;

    const result = await pool.query(
      SEL +
        (followingOnly
          ? `
        WHERE EXISTS(
          SELECT 1
          FROM follows
          WHERE follower = $1
          AND followee = v.user_id
        )`
          : '') +
        `
        ORDER BY v.created DESC
        LIMIT 50
      `,
      [me]
    );

    res.json(result.rows);
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحميل المنشورات'
    });
  }
});


/* =========================
   Upload Video
   (يدعم اختيار الجودة والفريمات عبر FFmpeg، ويعمل كمهمة خلفية يتابعها العميل)
========================= */

/* رفع ملف من القرص إلى Cloudinary بنفس أسلوب upload_stream الحالي */
const uploadFileToCloudinary = (filePath, resourceType, folder) =>
  new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      {
        resource_type: resourceType,
        folder
      },
      (error, result) => {
        if (error) {
          reject(error);
        } else {
          resolve(result);
        }
      }
    );

    const rs = fs.createReadStream(filePath);
    rs.on('error', reject);
    rs.pipe(stream);
  });

/* مقاسات الجودة (للفيديو الأفقي؛ يُقلب الصندوق تلقائيًا للفيديو الطولي) */
const QUALITY = {
  '8k': [7680, 4320],
  '4k': [3840, 2160],
  '2k': [2560, 1440],
  '1k': [1920, 1080],
  '720': [1280, 720]
};

const even = (x) => Math.max(2, Math.round(x / 2) * 2);

/*
  خطة المعالجة — بدون «رفع وهمي»:
  - الدقة: لا تُكبَّر أبدًا (scale ≤ 1) مع الحفاظ على النسبة.
  - الفريمات: تُخفَّض فقط إن كان الأصل أعلى من المطلوب، ولا تُولَّد إطارات وهمية.
*/
function planVideo(src, quality, fpsReq) {
  let w = src.w;
  let h = src.h;
  let scale = 1;
  let belowTarget = false;

  if (QUALITY[quality]) {
    const [bw, bh] = src.w >= src.h ? QUALITY[quality] : [QUALITY[quality][1], QUALITY[quality][0]];
    const raw = Math.min(bw / src.w, bh / src.h);
    belowTarget = raw > 1.001;
    scale = Math.min(1, raw);
  }

  const needScale = scale < 0.999;

  if (needScale) {
    w = even(src.w * scale);
    h = even(src.h * scale);
  }

  let fps = src.fps;
  let needFps = false;

  if (src.fps && fpsReq && src.fps > fpsReq * 1.02) {
    fps = fpsReq;
    needFps = true;
  }

  return { w, h, fps, needScale, needFps, belowTarget, transcode: needScale || needFps };
}

const parseFps = (s) => {
  const [a, b] = String(s || '').split('/').map(Number);
  if (!a || !b) return null;
  return Math.round((a / b) * 100) / 100;
};

const probeVideo = (file) =>
  new Promise((resolve) => {
    execFile(
      FFPROBE,
      [
        '-v', 'error',
        '-show_entries',
        'stream=codec_type,codec_name,width,height,avg_frame_rate,r_frame_rate:stream_tags=rotate:stream_side_data=rotation:format=duration',
        '-of', 'json',
        file
      ],
      { timeout: 30000, maxBuffer: 4 * 1024 * 1024 },
      (err, out) => {
        if (err) return resolve(null);

        try {
          const j = JSON.parse(out);
          const vs = (j.streams || []).find((s) => s.codec_type === 'video');
          const au = (j.streams || []).find((s) => s.codec_type === 'audio');

          if (!vs || !vs.width || !vs.height) return resolve(null);

          let rot = Number(vs.tags && vs.tags.rotate) || 0;
          const sd = (vs.side_data_list || []).find((x) => x.rotation !== undefined);
          if (sd) rot = Number(sd.rotation) || rot;

          const swap = Math.abs(rot) % 180 === 90;

          resolve({
            w: swap ? vs.height : vs.width,
            h: swap ? vs.width : vs.height,
            fps: parseFps(vs.avg_frame_rate) || parseFps(vs.r_frame_rate),
            duration: Number(j.format && j.format.duration) || 0,
            audio: au ? au.codec_name : null
          });
        } catch {
          resolve(null);
        }
      }
    );
  });

const runFfmpeg = (args) =>
  new Promise((resolve, reject) => {
    const p = spawn(FFMPEG, args, { stdio: ['ignore', 'ignore', 'pipe'] });
    let errTail = '';
    let timedOut = false;

    p.stderr.on('data', (d) => {
      errTail = (errTail + d).slice(-2000);
    });

    const t = setTimeout(() => {
      timedOut = true;
      p.kill('SIGKILL');
    }, PROCESS_TIMEOUT_MS);

    p.on('error', (e) => {
      clearTimeout(t);
      reject(e);
    });

    p.on('close', (code) => {
      clearTimeout(t);
      if (code === 0) resolve();
      else reject(new Error(timedOut ? 'ffmpeg timeout' : errTail || 'ffmpeg exit ' + code));
    });
  });

/* معالجة واحدة فقط في نفس الوقت لحماية السيرفر المجاني */
let procChain = Promise.resolve();
const enqueueProcess = (fn) => {
  const p = procChain.then(fn);
  procChain = p.catch(() => {});
  return p;
};

function buildFfmpegArgs(input, output, src, pl) {
  const filters = [];

  if (pl.needScale) filters.push(`scale=${pl.w}:${pl.h}:flags=lanczos`);
  if (pl.needFps) filters.push(`fps=${pl.fps}`);

  const args = [
    '-y', '-hide_banner', '-loglevel', 'error',
    '-i', input,
    '-map', '0:v:0',
    '-map', '0:a:0?',
    '-sn', '-dn'
  ];

  if (filters.length) args.push('-vf', filters.join(','));

  args.push(
    '-c:v', 'libx264',
    '-preset', FFMPEG_PRESET,
    '-crf', '18',
    '-pix_fmt', 'yuv420p',
    '-threads', FFMPEG_THREADS
  );

  /* الصوت: نسخ مباشر إن كان AAC (بدون فقد)، وإلا تحويل إلى AAC بجودة عالية */
  if (src.audio === 'aac') args.push('-c:a', 'copy');
  else args.push('-c:a', 'aac', '-b:a', '192k');

  args.push('-movflags', '+faststart', output);

  return args;
}

/* مهام الرفع في الذاكرة (يتابعها العميل عبر /api/videos/jobs/:id) */
const jobs = new Map();

setInterval(() => {
  const cutoff = Date.now() - 15 * 60 * 1000;
  for (const [id, j] of jobs) {
    if (j.created < cutoff && (j.status === 'done' || j.status === 'error')) jobs.delete(id);
  }
}, 5 * 60 * 1000).unref();

async function runVideoJob(job, file, caption, quality, fpsReq) {
  const tmp = [file.path];

  try {
    job.status = 'processing';

    const src = await probeVideo(file.path);

    let uploadPath = file.path;
    let uploadSize = file.size;
    let processed = false;
    let note = '';
    let orig = null;
    let final = null;

    if (!src) {
      note = 'تعذّر قراءة معلومات الفيديو، فنُشر كما هو دون تغيير.';
    } else {
      orig = { w: src.w, h: src.h, fps: src.fps };
      final = { w: src.w, h: src.h, fps: src.fps };

      const pl = planVideo(src, quality, fpsReq);

      if (pl.transcode) {
        if (src.w * src.h > MAX_PROCESS_PIXELS || src.duration > MAX_PROCESS_SECONDS) {
          note = 'حجم الفيديو أو مدته أكبر من حد المعالجة على هذا الخادم، فنُشر بجودته الأصلية.';
        } else {
          const out = path.join(os.tmpdir(), 'pulse-out-' + crypto.randomBytes(8).toString('hex') + '.mp4');
          tmp.push(out);

          try {
            await enqueueProcess(() => runFfmpeg(buildFfmpegArgs(file.path, out, src, pl)));

            const outSize = fs.statSync(out).size;

            if (outSize > CLOUDINARY_MAX_BYTES) {
              note = 'الناتج بعد المعالجة أكبر من حد الرفع، فنُشر الفيديو بجودته الأصلية.';
            } else {
              uploadPath = out;
              uploadSize = outSize;
              processed = true;

              const o = await probeVideo(out);
              final = o
                ? { w: o.w, h: o.h, fps: o.fps || pl.fps }
                : { w: pl.w, h: pl.h, fps: pl.fps };
            }
          } catch (e) {
            console.error('فشل FFmpeg:', e.message);
            note = 'تعذّرت معالجة الفيديو على الخادم، فنُشر بجودته الأصلية.';
          }
        }
      }

      if (!processed && !note && pl.belowTarget) {
        note = 'الفيديو الأصلي أقل من الجودة المطلوبة، فنُشر بدقته الأصلية دون تكبير وهمي.';
      }
    }

    job.status = 'uploading';

    const uploaded = await uploadFileToCloudinary(uploadPath, 'video', 'pulse');

    const meta = {
      orig,
      requested: { quality, fps: fpsReq },
      final,
      duration: src ? Math.round(src.duration * 10) / 10 : null,
      size_orig: file.size,
      size_final: uploadSize,
      processed
    };

    await pool.query(
      `
      INSERT INTO videos(user_id, file, caption, meta)
      VALUES($1, $2, $3, $4)
      `,
      [job.userId, uploaded.secure_url, caption, JSON.stringify(meta)]
    );

    job.result = { orig, requested: meta.requested, final, processed, note };
    job.status = 'done';
  } catch (err) {
    console.error(err);
    job.status = 'error';
    job.error = 'تعذر رفع الفيديو';
  } finally {
    tmp.forEach(rmFile);
  }
}

app.post(
  '/api/videos',
  (req, res, next) => (must(req, res) ? next() : 0),
  up.single('video'),
  async (req, res) => {
    try {
      if (!req.file) {
        return res.status(400).json({
          error: 'اختر ملف فيديو'
        });
      }

      let busy = 0;
      for (const j of jobs.values()) {
        if (j.userId === req.u.id && (j.status === 'processing' || j.status === 'uploading')) busy++;
      }

      if (busy >= 1) {
        rmFile(req.file.path);
        return res.status(429).json({
          error: 'لديك فيديو قيد المعالجة بالفعل، انتظر حتى ينتهي'
        });
      }

      const quality = QUALITY[req.body.quality] ? req.body.quality : 'auto';
      const fpsReq = Number(req.body.fps) === 30 ? 30 : 60;
      const caption = String(req.body.caption || '').slice(0, 200);

      const id = crypto.randomBytes(8).toString('hex');
      const job = { id, userId: req.u.id, status: 'processing', created: Date.now() };
      jobs.set(id, job);

      runVideoJob(job, req.file, caption, quality, fpsReq);

      res.json({
        ok: true,
        job: id
      });
    } catch (err) {
      rmFile(req.file && req.file.path);
      console.error(err);

      res.status(500).json({
        error: 'تعذر رفع الفيديو'
      });
    }
  }
);

app.get('/api/videos/jobs/:id', (req, res) => {
  if (!must(req, res)) return;

  const j = jobs.get(req.params.id);

  if (!j || j.userId !== req.u.id) {
    return res.status(404).json({ error: 'المهمة غير موجودة' });
  }

  res.json({
    status: j.status,
    error: j.error || null,
    result: j.result || null
  });
});

/* =========================
   Delete Video
========================= */
app.delete('/api/videos/:id', async (req, res) => {
  if (!must(req, res)) return;

  try {
    const videoId = Number(req.params.id);

    const result = await pool.query(
      `
      SELECT id, user_id, file
      FROM videos
      WHERE id = $1
      `,
      [videoId]
    );

    if (result.rowCount === 0) {
      return res.status(404).json({
        error: 'الفيديو غير موجود'
      });
    }

    const video = result.rows[0];

    if (video.user_id !== req.u.id) {
      return res.status(403).json({
        error: 'لا يمكنك حذف هذا الفيديو'
      });
    }

    await pool.query(
      `DELETE FROM likes WHERE video_id = $1`,
      [videoId]
    );

    await pool.query(
      `DELETE FROM comments WHERE video_id = $1`,
      [videoId]
    );

    await pool.query(
      `DELETE FROM videos WHERE id = $1`,
      [videoId]
    );

    res.json({
      ok: true
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر حذف الفيديو'
    });
  }
});

/* =========================
   Like
========================= */

app.post('/api/videos/:id/like', async (req, res) => {
  if (!must(req, res)) return;

  try {
    const userId = req.u.id;
    const videoId = Number(req.params.id);

    const deleted = await pool.query(
      `
      DELETE FROM likes
      WHERE user_id = $1
      AND video_id = $2
      `,
      [userId, videoId]
    );

    let liked;

    if (deleted.rowCount === 0) {
      await pool.query(
        `
        INSERT INTO likes(user_id, video_id)
        VALUES($1, $2)
        ON CONFLICT DO NOTHING
        `,
        [userId, videoId]
      );

      liked = true;
    } else {
      liked = false;
    }

    const count = await pool.query(
      `
      SELECT COUNT(*) AS c
      FROM likes
      WHERE video_id = $1
      `,
      [videoId]
    );

    res.json({
      liked,
      likes: Number(count.rows[0].c)
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحديث الإعجاب'
    });
  }
});


/* =========================
   Comments
========================= */

app.get('/api/videos/:id/comments', async (req, res) => {
  try {
    const result = await pool.query(
      `
      SELECT
        c.body,
        u.name
      FROM comments c
      JOIN users u ON u.id = c.user_id
      WHERE c.video_id = $1
      ORDER BY c.id
      `,
      [Number(req.params.id)]
    );

    res.json(result.rows);
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحميل التعليقات'
    });
  }
});


app.post('/api/videos/:id/comments', async (req, res) => {
  if (!must(req, res)) return;

  try {
    const body = String(req.body.body || '')
      .trim()
      .slice(0, 300);

    if (!body) {
      return res.status(400).json({
        error: 'اكتب تعليقًا'
      });
    }

    await pool.query(
      `
      INSERT INTO comments(user_id, video_id, body)
      VALUES($1, $2, $3)
      `,
      [
        req.u.id,
        Number(req.params.id),
        body
      ]
    );

    res.json({
      ok: true
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر إضافة التعليق'
    });
  }
});


/* =========================
   Follow
========================= */

app.post('/api/users/:name/follow', async (req, res) => {
  if (!must(req, res)) return;

  try {
    const target = await pool.query(
      `
      SELECT id
      FROM users
      WHERE name = $1
      `,
      [req.params.name]
    );

    const t = target.rows[0];

    if (!t || t.id === req.u.id) {
      return res.status(400).json({
        error: 'غير ممكن'
      });
    }

    const deleted = await pool.query(
      `
      DELETE FROM follows
      WHERE follower = $1
      AND followee = $2
      `,
      [
        req.u.id,
        t.id
      ]
    );

    let following;

    if (deleted.rowCount === 0) {
      await pool.query(
        `
        INSERT INTO follows(follower, followee)
        VALUES($1, $2)
        ON CONFLICT DO NOTHING
        `,
        [
          req.u.id,
          t.id
        ]
      );

      following = true;
    } else {
      following = false;
    }

    res.json({
      following
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحديث المتابعة'
    });
  }
});


/* =========================
   User Profile
========================= */

app.get('/api/users/:name', async (req, res) => {
  try {
    const userResult = await pool.query(
      `
      SELECT id, name
      FROM users
      WHERE name = $1
      `,
      [req.params.name]
    );

    const u = userResult.rows[0];

    if (!u) {
      return res.status(404).json({
        error: 'غير موجود'
      });
    }

    const followers = await pool.query(
      `
      SELECT COUNT(*) AS c
      FROM follows
      WHERE followee = $1
      `,
      [u.id]
    );

    const following = await pool.query(
      `
      SELECT COUNT(*) AS c
      FROM follows
      WHERE follower = $1
      `,
      [u.id]
    );

    const videos = await pool.query(
      SEL +
        `
        WHERE v.user_id = $2
        ORDER BY v.created DESC
        `,
      [
        req.u ? req.u.id : 0,
        u.id
      ]
    );

    res.json({
      name: u.name,
      followers: Number(followers.rows[0].c),
      following: Number(following.rows[0].c),
      videos: videos.rows
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحميل الحساب'
    });
  }
});


/* =========================
   Stories
========================= */

/* حذف ملف القصة من Cloudinary — فقط إن كان داخل مجلد pulse/stories (آمن) */
const destroyStoryAsset = (row) => {
  if (!row.public_id || !row.public_id.startsWith('pulse/stories/')) {
    return Promise.resolve();
  }

  return cloudinary.uploader
    .destroy(row.public_id, {
      resource_type: row.type === 'video' ? 'video' : 'image',
      invalidate: true
    })
    .catch((e) => console.error('تعذر حذف ملف القصة من Cloudinary:', e.message || e));
};

/* القصص النشطة فقط (expires_at > NOW())، مجمّعة حسب المستخدم */
app.get('/api/stories', async (req, res) => {
  try {
    const me = req.u ? req.u.id : 0;

    // المسجّل: قصصه + قصص من يتابعهم. الزائر: القصص العامة النشطة.
    const scope = req.u
      ? `AND (s.user_id = $1 OR EXISTS(
           SELECT 1 FROM follows
           WHERE follower = $1 AND followee = s.user_id
         ))`
      : '';

    const result = await pool.query(
      `
      SELECT
        s.id,
        s.file,
        s.type,
        s.created_at,
        s.expires_at,
        u.name,
        (s.user_id = $1) AS mine
      FROM stories s
      JOIN users u ON u.id = s.user_id
      WHERE s.expires_at > NOW()
      ${scope}
      ORDER BY s.created_at DESC
      LIMIT 500
      `,
      [me]
    );

    const map = new Map();

    for (const row of result.rows.reverse()) {
      if (!map.has(row.name)) {
        map.set(row.name, { name: row.name, mine: row.mine, stories: [] });
      }

      map.get(row.name).stories.push({
        id: row.id,
        file: row.file,
        type: row.type,
        created_at: row.created_at,
        expires_at: row.expires_at
      });
    }

    const last = (g) => new Date(g.stories[g.stories.length - 1].created_at).getTime();

    const groups = [...map.values()].sort((a, b) => {
      if (a.mine !== b.mine) return a.mine ? -1 : 1;
      return last(b) - last(a);
    });

    res.json(groups);
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحميل القصص'
    });
  }
});

app.post(
  '/api/stories',
  (req, res, next) => (must(req, res) ? next() : 0),
  storyUp.single('file'),
  async (req, res) => {
    const tmpPath = req.file && req.file.path;

    try {
      if (!req.file) {
        return res.status(400).json({
          error: 'اختر صورة أو فيديو'
        });
      }

      const type = req.file.mimetype.startsWith('video/') ? 'video' : 'image';

      if (type === 'image' && req.file.size > 20 * 1024 * 1024) {
        return res.status(400).json({
          error: 'الصورة أكبر من 20 ميجا'
        });
      }

      const uploaded = await uploadFileToCloudinary(tmpPath, type, 'pulse/stories');

      // user_id يؤخذ من التوكن فقط، ومدة الانتهاء تُحدَّد في الخادم
      await pool.query(
        `
        INSERT INTO stories(user_id, file, type, public_id, expires_at)
        VALUES($1, $2, $3, $4, NOW() + INTERVAL '24 hours')
        `,
        [req.u.id, uploaded.secure_url, type, uploaded.public_id]
      );

      res.json({
        ok: true
      });
    } catch (err) {
      console.error(err);

      res.status(500).json({
        error: 'تعذر نشر القصة'
      });
    } finally {
      rmFile(tmpPath);
    }
  }
);

app.delete('/api/stories/:id', async (req, res) => {
  if (!must(req, res)) return;

  try {
    const id = Number(req.params.id);

    if (!Number.isInteger(id)) {
      return res.status(400).json({
        error: 'معرّف غير صالح'
      });
    }

    const result = await pool.query(
      `
      SELECT id, user_id, type, public_id
      FROM stories
      WHERE id = $1
      `,
      [id]
    );

    if (result.rowCount === 0) {
      return res.status(404).json({
        error: 'القصة غير موجودة'
      });
    }

    const story = result.rows[0];

    if (story.user_id !== req.u.id) {
      return res.status(403).json({
        error: 'لا يمكنك حذف هذه القصة'
      });
    }

    await pool.query(`DELETE FROM stories WHERE id = $1`, [id]);

    destroyStoryAsset(story);

    res.json({
      ok: true
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر حذف القصة'
    });
  }
});

/* تنظيف دوري داخل التطبيق (بدون Cron خارجي) */
async function cleanupStories() {
  try {
    const result = await pool.query(
      `
      DELETE FROM stories
      WHERE expires_at <= NOW()
      RETURNING type, public_id
      `
    );

    for (const row of result.rows) {
      await destroyStoryAsset(row);
    }

    if (result.rowCount) {
      console.log(`تم حذف ${result.rowCount} قصة منتهية.`);
    }
  } catch (err) {
    console.error('تعذر تنظيف القصص المنتهية:', err.message || err);
  }
}


/* =========================
   Static Files
========================= */

app.use('/uploads', express.static('uploads'));

app.use(express.static('public'));


/* =========================
   Error Handler
========================= */

app.use((err, req, res, next) => {
  console.error(err);

  res.status(400).json({
    error:
      err.code === 'LIMIT_FILE_SIZE'
        ? 'الفيديو أكبر من 100 ميجا'
        : 'خطأ في الطلب'
  });
});


/* =========================
   Start Server
========================= */

const PORT = process.env.PORT || 3000;

initDB()
  .then(() => {
    app.listen(PORT, () => {
      console.log(`يعمل على http://localhost:${PORT}`);
    });

    cleanupStories();
    setInterval(cleanupStories, 30 * 60 * 1000).unref();
  })
  .catch((err) => {
    console.error('فشل الاتصال بقاعدة البيانات:', err);
    process.exit(1);
  });
