
const express = require('express');
const { Pool } = require('pg');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

const SECRET =
  process.env.JWT_SECRET || crypto.randomBytes(32).toString('hex');

if (!process.env.JWT_SECRET) {
  console.warn(
    'تنبيه: JWT_SECRET غير مضبوط، سيتسجّل خروج الجميع عند كل إعادة تشغيل.'
  );
}

if (!process.env.DATABASE_URL) {
  console.error('خطأ: DATABASE_URL غير مضبوط.');
  process.exit(1);
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
});

fs.mkdirSync('uploads', { recursive: true });

async function initDB() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT UNIQUE NOT NULL,
      pass TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS videos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      file TEXT NOT NULL,
      caption TEXT,
      created BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())
    );

    CREATE TABLE IF NOT EXISTS likes (
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
      PRIMARY KEY (user_id, video_id)
    );

    CREATE TABLE IF NOT EXISTS comments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
      body TEXT NOT NULL,
      created BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())
    );

    CREATE TABLE IF NOT EXISTS follows (
      follower INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      followee INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      PRIMARY KEY (follower, followee)
    );
  `);

  console.log('تم الاتصال بقاعدة بيانات Neon بنجاح.');
}
const app = express();

app.use(express.json());

app.use((req, res, next) => {
  try {
    const auth = (req.headers.authorization || '').replace('Bearer ', '');
    req.u = jwt.verify(auth, SECRET);
  } catch {
    req.u = null;
  }

  next();
});

const must = (req, res) =>
  req.u ||
  (res.status(401).json({ error: 'سجّل الدخول أولًا' }), null);

const up = multer({
  storage: multer.diskStorage({
    destination: 'uploads',
    filename: (req, file, cb) => {
      cb(
        null,
        crypto.randomUUID() +
          path.extname(file.originalname).toLowerCase().slice(0, 6)
      );
    }
  }),
  limits: {
    fileSize: 100 * 1024 * 1024
  },
  fileFilter: (req, file, cb) => {
    cb(null, /^video\//.test(file.mimetype));
  }
});

const token = (u) =>
  jwt.sign(
    {
      id: u.id,
      name: u.name
    },
    SECRET,
    {
      expiresIn: '30d'
    }
  );

const cred = (b) =>
  /^[A-Za-z0-9_]{3,20}$/.test(b.name || '') &&
  (b.pass || '').length >= 6;


/* =========================
   Register
========================= */

app.post('/api/register', async (req, res) => {
  if (!cred(req.body)) {
    return res.status(400).json({
      error:
        'الاسم 3-20 حرفًا إنجليزيًا/أرقام/_ وكلمة المرور 6 على الأقل'
    });
  }

  try {
    const hashed = bcrypt.hashSync(req.body.pass, 10);

    const result = await pool.query(
      `
      INSERT INTO users(name, pass)
      VALUES($1, $2)
      RETURNING id, name
      `,
      [req.body.name, hashed]
    );

    const u = result.rows[0];

    res.json({
      token: token(u),
      name: u.name
    });
  } catch (err) {
    if (err.code === '23505') {
      return res.status(409).json({
        error: 'الاسم مستخدم'
      });
    }

    console.error(err);
    res.status(500).json({
      error: 'حدث خطأ في الخادم'
    });
  }
});


/* =========================
   Login
========================= */

app.post('/api/login', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT * FROM users WHERE name = $1',
      [req.body.name || '']
    );

    const u = result.rows[0];

    if (!u || !bcrypt.compareSync(req.body.pass || '', u.pass)) {
      return res.status(401).json({
        error: 'بيانات الدخول غير صحيحة'
      });
    }

    res.json({
      token: token(u),
      name: u.name
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'حدث خطأ في الخادم'
    });
  }
});


/* =========================
   Feed
========================= */

const SEL = `
  SELECT
    v.id,
    v.file,
    v.caption,
    u.name,

    (SELECT COUNT(*)
     FROM likes
     WHERE video_id = v.id) AS likes,

    (SELECT COUNT(*)
     FROM comments
     WHERE video_id = v.id) AS comments,

    EXISTS(
      SELECT 1
      FROM likes
      WHERE video_id = v.id
      AND user_id = $1
    ) AS liked,

    EXISTS(
      SELECT 1
      FROM follows
      WHERE follower = $1
      AND followee = v.user_id
    ) AS following

  FROM videos v
  JOIN users u ON u.id = v.user_id
`;


app.get('/api/feed', async (req, res) => {
  try {
    const me = req.u ? req.u.id : 0;

    const result = await pool.query(
      SEL + `
        ORDER BY v.created DESC
        LIMIT 50
      `,
      [me]
    );

    res.json(result.rows);
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحميل المنشورات'
    });
  }
});


/* =========================
   Upload Video
========================= */

app.post(
  '/api/videos',
  (req, res, next) => (must(req, res) ? next() : 0),
  up.single('video'),
  async (req, res) => {
    try {
      if (!req.file) {
        return res.status(400).json({
          error: 'اختر ملف فيديو'
        });
      }

      await pool.query(
        `
        INSERT INTO videos(user_id, file, caption)
        VALUES($1, $2, $3)
        `,
        [
          req.u.id,
          req.file.filename,
          String(req.body.caption || '').slice(0, 200)
        ]
      );

      res.json({
        ok: true
      });
    } catch (err) {
      console.error(err);

      res.status(500).json({
        error: 'تعذر رفع الفيديو'
      });
    }
  }
);


/* =========================
   Like
========================= */

app.post('/api/videos/:id/like', async (req, res) => {
  if (!must(req, res)) return;

  try {
    const userId = req.u.id;
    const videoId = Number(req.params.id);

    const deleted = await pool.query(
      `
      DELETE FROM likes
      WHERE user_id = $1
      AND video_id = $2
      `,
      [userId, videoId]
    );

    let liked;

    if (deleted.rowCount === 0) {
      await pool.query(
        `
        INSERT INTO likes(user_id, video_id)
        VALUES($1, $2)
        ON CONFLICT DO NOTHING
        `,
        [userId, videoId]
      );

      liked = true;
    } else {
      liked = false;
    }

    const count = await pool.query(
      `
      SELECT COUNT(*) AS c
      FROM likes
      WHERE video_id = $1
      `,
      [videoId]
    );

    res.json({
      liked,
      likes: Number(count.rows[0].c)
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحديث الإعجاب'
    });
  }
});


/* =========================
   Comments
========================= */

app.get('/api/videos/:id/comments', async (req, res) => {
  try {
    const result = await pool.query(
      `
      SELECT
        c.body,
        u.name
      FROM comments c
      JOIN users u ON u.id = c.user_id
      WHERE c.video_id = $1
      ORDER BY c.id
      `,
      [Number(req.params.id)]
    );

    res.json(result.rows);
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحميل التعليقات'
    });
  }
});


app.post('/api/videos/:id/comments', async (req, res) => {
  if (!must(req, res)) return;

  try {
    const body = String(req.body.body || '')
      .trim()
      .slice(0, 300);

    if (!body) {
      return res.status(400).json({
        error: 'اكتب تعليقًا'
      });
    }

    await pool.query(
      `
      INSERT INTO comments(user_id, video_id, body)
      VALUES($1, $2, $3)
      `,
      [
        req.u.id,
        Number(req.params.id),
        body
      ]
    );

    res.json({
      ok: true
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر إضافة التعليق'
    });
  }
});


/* =========================
   Follow
========================= */

app.post('/api/users/:name/follow', async (req, res) => {
  if (!must(req, res)) return;

  try {
    const target = await pool.query(
      `
      SELECT id
      FROM users
      WHERE name = $1
      `,
      [req.params.name]
    );

    const t = target.rows[0];

    if (!t || t.id === req.u.id) {
      return res.status(400).json({
        error: 'غير ممكن'
      });
    }

    const deleted = await pool.query(
      `
      DELETE FROM follows
      WHERE follower = $1
      AND followee = $2
      `,
      [
        req.u.id,
        t.id
      ]
    );

    let following;

    if (deleted.rowCount === 0) {
      await pool.query(
        `
        INSERT INTO follows(follower, followee)
        VALUES($1, $2)
        ON CONFLICT DO NOTHING
        `,
        [
          req.u.id,
          t.id
        ]
      );

      following = true;
    } else {
      following = false;
    }

    res.json({
      following
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحديث المتابعة'
    });
  }
});


/* =========================
   User Profile
========================= */

app.get('/api/users/:name', async (req, res) => {
  try {
    const userResult = await pool.query(
      `
      SELECT id, name
      FROM users
      WHERE name = $1
      `,
      [req.params.name]
    );

    const u = userResult.rows[0];

    if (!u) {
      return res.status(404).json({
        error: 'غير موجود'
      });
    }

    const followers = await pool.query(
      `
      SELECT COUNT(*) AS c
      FROM follows
      WHERE followee = $1
      `,
      [u.id]
    );

    const following = await pool.query(
      `
      SELECT COUNT(*) AS c
      FROM follows
      WHERE follower = $1
      `,
      [u.id]
    );

    const videos = await pool.query(
      SEL +
        `
        WHERE v.user_id = $2
        ORDER BY v.created DESC
        `,
      [
        req.u ? req.u.id : 0,
        u.id
      ]
    );

    res.json({
      name: u.name,
      followers: Number(followers.rows[0].c),
      following: Number(following.rows[0].c),
      videos: videos.rows
    });
  } catch (err) {
    console.error(err);

    res.status(500).json({
      error: 'تعذر تحميل الحساب'
    });
  }
});


/* =========================
   Static Files
========================= */

app.use('/uploads', express.static('uploads'));

app.use(express.static('public'));


/* =========================
   Error Handler
========================= */

app.use((err, req, res, next) => {
  console.error(err);

  res.status(400).json({
    error:
      err.code === 'LIMIT_FILE_SIZE'
        ? 'الفيديو أكبر من 100 ميجا'
        : 'خطأ في الطلب'
  });
});


/* =========================
   Start Server
========================= */

const PORT = process.env.PORT || 3000;

initDB()
  .then(() => {
    app.listen(PORT, () => {
      console.log(`يعمل على http://localhost:${PORT}`);
    });
  })
  .catch((err) => {
    console.error('فشل الاتصال بقاعدة البيانات:', err);
    process.exit(1);
  });
